steps:
# Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

# Build
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
# Functionss
- name: 'gcr.io/portfolio-showcase-website/firebase'
  args: ['deploy', '--only', 'functions']
# Deploy
- name: 'gcr.io/portfolio-showcase-website/firebase'
  args: ['deploy', '--only', 'hosting']