steps:
# Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

# Build
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']

- id: 'functions npm install'
  name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'functions'

- id: "deploy firebase"
  name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy', '--only', 'functions', '--project=portfolio-showcase-website']
# Deploy
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy', '--only', 'hosting']